---
- name: Create Portainer volume
  community.docker.docker_volume:
    name: "{{ portainer_volume }}"
    state: present

- name: Create basic authentication credentials
  ansible.builtin.command: htpasswd -nbB "{{ portainer_auth_user }}" "{{ portainer_auth_password }}"
  register: portainer_auth
  no_log: true
  changed_when: false

- name: Deploy Portainer service
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    state: started
    restart_policy: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ portainer_volume }}:/data"
    env:
      ADMIN_PASSWORD: "{{ portainer_auth_password }}"
    networks:
      - name: "{{ traefik_network }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer-dashboard.rule: "Host(`portainer.wefp.ru`)"
      traefik.http.services.portainer-dashboard.loadbalancer.server.port: "9000"
      traefik.http.routers.portainer-dashboard.entrypoints: "websecure"
      traefik.http.routers.portainer-dashboard.tls.certresolver: "le"

      # Authentication
      traefik.http.routers.portainer-dashboard.middlewares: "portainer-dashboard-auth,secure-headers"
      traefik.http.middlewares.portainer-dashboard-auth.basicauth.users: "{{ portainer_auth.stdout | trim }}"
