version: "3.2"
services:
  mysql:
    image: mysql:5.7.42
    ports:
      - "3306:3306"
    command:
      - 'mysqld'
      - '--default-authentication-plugin=mysql_native_password'
      - '--bind-address=0.0.0.0'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: awrfpiouhafdsoihgrp0ihgearoihagreihoagfoihasdlkjn
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_net

networks:
  mysql_net:
    external: true

volumes:
  mysql_data:
