version: "3.2"
services:
  mysql:
    image: mysql:5.7.42
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: awrfpiouhafdsoihgrp0ihgearoihagreihoagfoihasdlkjn
