entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"

api:
  dashboard: true

providers:
  docker:
    watch: true
    swarmMode: true
    exposedByDefault: false
  file:
    filename: /etc/traefik/routes.yaml
    watch: true

log:
  level: DEBUG

accessLog: {}

certificatesResolvers:
  le:
    acme:
      email: revv@wefp.ru
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web
